src/dropzone/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url


urlpatterns = patterns(
    'src.dropzone.views',
    url(r'^$', 'index', name='index'),
    url(r'^upload/$', 'upload', name='upload'),
)

src/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^accounts/login/$', login, {'template_name': 'frontend/login.html'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dropzone/', include('src.dropzone.urls', namespace='dropzone')),
    url(r'^galleria/', include('src.galleria.urls', namespace='galleria')),
    url(r'^', include('src.frontend.urls', namespace='frontend')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT, }), )

src/dropzone/models.py
# -*- coding: utf-8 -*-

from base64 import b64encode
from dateutil import parser
from hashlib import sha1
from os.path import splitext

from django.db import models
from django.utils.translation import ugettext_lazy as _

from . import get_exif

S10K = 10 * 1024


def upload_photos_dir(instance, filename):
    u"""Возвращает путь для загружаемого файла, учитывая данные exif."""
    f = instance.resource.file
    f.seek(0)
    first10k = f.read(S10K if f.size > S10K else f.size)
    filehash = sha1(b64encode(first10k)).hexdigest()
    ext = splitext(filename)[1]
    exif = get_exif(f)
    ts = exif.get('DateTimeOriginal')
    if ts:
        ts = parser.parse(ts)
        return u'dropzone/photos/%s/%s/%s/%s%s' % (ts.year, ts.month, ts.day, filehash, ext)
    else:
        return u'dropzone/photos/no-exif/%s%s' % (filehash, ext)


class Photo(models.Model):
    EXIF_NOPE = 1
    EXIF_HF = 2
    EXIF_UD = 3
    EXIF_VF = 4
    EXIF_VFR = 5
    EXIF_R = 6
    EXIF_HFR = 7
    EXIF_L = 8
    EXIF_ORIENTATION_CHOICES = (
        (EXIF_NOPE, _('No action')),
        (EXIF_HF, _('Horizontal flip')),
        (EXIF_UD, _('Left 180 degrees')),
        (EXIF_VF, _('Vertical flip')),
        (EXIF_VFR, _('Vertical flip and right 90 degrees')),
        (EXIF_R, _('Right 90 degrees')),
        (EXIF_HFR, _('Horizontal flip and right 90 degrees')),
        (EXIF_L, _('Left 90 degrees')), )

    resource = models.FileField(upload_to=upload_photos_dir, max_length=256, verbose_name=_('Resource'))
    file_name = models.CharField(max_length=256, verbose_name=_('Name'))
    file_type = models.CharField(max_length=80, verbose_name=_('MIME'))
    file_size = models.PositiveIntegerField(default=0, verbose_name=_('Size'))
    orientation = models.PositiveIntegerField(default=1, verbose_name=_('Orientation'), choices=EXIF_ORIENTATION_CHOICES)
    uploaded_by = models.ForeignKey('auth.User', related_name=u'uploaded_by', verbose_name=_('Uploader'))
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-uploaded_at', )
        verbose_name = _(u'Resource')
        verbose_name_plural = _(u'Resources')
        ordering = ('-uploaded_at', )

    def __unicode__(self):
        return self.file_name

    def save(self, user):
        f = self.resource.file
        self.uploaded_by = user
        self.file_name = f.name
        self.file_type = f.content_type
        self.file_size = f.size
        exif = get_exif(self.resource.file)
        self.orientation = exif.get('Orientation', 1)
        super(Photo, self).save()

src/dropzone/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm

from . models import Photo


class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ('resource', )

src/dropzone/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.views.generic.simple import direct_to_template

from . import JsonResponse
from . forms import PhotoForm


@login_required
def index(request):
    context = {}
    return direct_to_template(request, 'dropzone/index.html', context)


@login_required
def upload(request):
    status = 400
    response = None
    form = PhotoForm(request.POST, request.FILES)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.name = obj.resource.name
        obj.save(request.user)
        status = 200
        response = {'success': 200}
    else:
        response = {'error': 400}
        response.update({'errors': form.errors})
    return JsonResponse(response, status=status)

src/dropzone/templates/dropzone/index.html
{% extends "base.html" %}

{% load i18n staticfiles %}
{% load url from future %}

{% block page_title %}{% trans "DropZone" %}{% endblock %}

{% block extra_css %}{{ block.super }}
    <link rel="stylesheet" href="{% static "dropzone/css/basic.css" %}" />
    <link rel="stylesheet" href="{% static "dropzone/css/dropzone.css" %}" />
{% endblock %}

{% block extra_js %}{{ block.super }}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
    <script src="{% static "dropzone/js/jquery.cookie.js" %}"></script>
    <script src="{% static "dropzone/js/dropzone.js" %}"></script>
{% endblock %}

{% block extra_js_bottom %}{{ block.super }}
    <script>
    Dropzone.options.formDropzone = {
        paramName: "resource",
        maxFilesize: 10,
        init: function() {
            this.on('sending', function(file, xhr, formData) {
                var csrftoken = $.cookie('csrftoken');
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            });
        }
    };
    </script>
{% endblock %}

{% block body %}
    {% include "frontend/includes/navbar.html" %}

<div class="container">
    <div class="bg-image">
        <img src="http://twitter.github.io/bootstrap/assets/img/examples/slide-01.jpg" alt="">
        <div class="spacer120"></div>
    </div>
</div>

<div class="container marketing">
    <div id="dropzone">
        <form action="{% url 'dropzone:upload' %}"
            class="dropzone"
            id="form-dropzone"></form>
    </div>

    {% include "frontend/includes/footer.html" %}
</div><!-- /.container -->
{% endblock %}