src/frontend/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url


urlpatterns = patterns(
    'src.frontend.views',
    url(r'^$', 'index', name='index'),
)

src/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^accounts/login/$', login, {'template_name': 'frontend/login.html'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dropzone/', include('src.dropzone.urls', namespace='dropzone')),
    url(r'^galleria/', include('src.galleria.urls', namespace='galleria')),
    url(r'^', include('src.frontend.urls', namespace='frontend')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT, }), )

src/frontend/forms.py
# -*- coding: utf-8 -*-

from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit

src/frontend/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.views.generic.simple import direct_to_template


@login_required
def index(request):
    context = {}
    return direct_to_template(request, 'frontend/index.html', context)

src/frontend/templates/frontend/includes/carousel.html
{% load i18n %}
{% load url from future %}
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://twitter.github.io/bootstrap/assets/img/examples/slide-01.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>{% trans "Upload your photos" %}</h1>
          <p class="lead">
            {%blocktrans %}You may easily upload many photos at once with DropZone page.{% endblocktrans %}
          </p>
          <a class="btn btn-large btn-primary" href="{% url 'dropzone:index' %}">{% trans "Visit a DropZone" %}</a>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://twitter.github.io/bootstrap/assets/img/examples/slide-02.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>{% trans "Register your relatives" %}</h1>
          <p class="lead">
            {% blocktrans %}Keep the memory about your relatives and your origin. Assign photos to known people.{% endblocktrans %}
          </p>
          <a class="btn btn-large btn-primary" href="#">{% trans "Register them" %}</a>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://twitter.github.io/bootstrap/assets/img/examples/slide-03.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>{% trans "Look at relatives" %}</h1>
          <p class="lead">
            {% blocktrans %}The full featured gallery service is for you.{% endblocktrans %}
          </p>
          <a class="btn btn-large btn-primary" href="{% url 'galleria:index' %}">{% trans "Go to Gallery" %}</a>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

src/frontend/templates/frontend/includes/footer.html
<!-- FOOTER -->
<footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2013 Ruslan Popov &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

src/frontend/templates/frontend/includes/navbar.html
{% load i18n %}
{% load url from future %}
<div class="navbar-wrapper">
  <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
  <div class="container">

    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="{% url 'frontend:index' %}">{% trans "Relatives" %}</a>
        <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="active"><a href="#">{% trans "Home" %}</a></li>
            <li><a href="{% url 'dropzone:index' %}">{% trans "Drop Zone" %}</a></li>
            <li><a href="#relatives">{% trans "People" %}</a></li>
            <li><a href="{% url 'galleria:index' %}">{% trans "Gallery" %}</a></li>
            <li><a href="#about">{% trans "About" %}</a></li>
            <li><a href="#contact">{% trans "Contact" %}</a></li>
            <!-- Read about Bootstrap dropdowns at http://twitter.github.com/bootstrap/javascript.html#dropdowns -->
            {% comment %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            {% endcomment %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar -->
  </div> <!-- /.container -->
</div><!-- /.navbar-wrapper -->